platform :ios, '9.0'
use_frameworks!

def base_db_dependencies
    pod 'TBXML', '~> 1.5'
    pod 'AFNetworking', '~> 4.0'
    pod 'GTMNSStringHTMLAdditions', '~> 0.2.1'
    pod 'Mantle', '~> 2.1.0'
    pod 'GoogleMaps', '~> 3.7.0'
    pod 'MBProgressHUD', '~> 1.1.0'
end

target 'MeinBahnhofOpenSource' do
    base_db_dependencies
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            target.build_settings(configuration.name)['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
